Adding 2 files to lifecycle in examples folder
test-network-function/cnf-certification-test-partner pull request #213
Opened 2023-02-14 18:45 UTC by shimritproj

Regarding PR #751 in CNF repo, Adding 2 files to lifecycle in examples folder.

2023-02-14 19:44 UTC, sebrandon1 approved these changes

2023-02-14 22:30 UTC, edcdavid approved these changes
I would merge these 2 files and call the combined file: local_storage_fail.yaml

2023-02-14 22:31 UTC, edcdavid requested changes
I would merge these 2 files and call the combined file: local_storage_fail.yaml

2023-02-16 15:07 UTC, edcdavid approved these changes

2023-02-16 15:18 UTC, merged